# Generated by Django 5.2.7 on 2025-10-09 16:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('partner_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('TURO', 'Turo'), ('UBER', 'Uber'), ('AMAZON', 'Amazon'), ('OTHER', 'Other')], default='TURO', max_length=12)),
                ('paid_at', models.DateField()),
                ('amount_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('owner_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('partner_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('week_start', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
    ]
