# Generated by Django 5.2.7 on 2025-10-21 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(blank=True, help_text='Leave blank for a global expense (applies 100% to you).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
